# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20170526_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('recibio', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fechadeposito', models.DateField(blank=True, null=True)),
                ('codigodeposito', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_oficina', models.DateField()),
                ('fecha_ingreso_digecam', models.DateField(blank=True, null=True)),
                ('fecha_cita', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('recibio', models.CharField(max_length=100)),
                ('entrego', models.CharField(max_length=50)),
                ('tenencias', models.PositiveIntegerField()),
                ('estatus', models.CharField(max_length=6)),
                ('descripcion_estatus', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to='archivos/%Y/%m/%d')),
                ('cobro', models.ManyToManyField(to='sistema.Cobro')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2300)])),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operacionmes',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Empresa'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='operacionmes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.OperacionMes'),
        ),
        migrations.AddField(
            model_name='abono',
            name='operacionmes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.OperacionMes'),
        ),
        migrations.AlterUniqueTogether(
            name='operacionmes',
            unique_together=set([('mes', 'anio')]),
        ),
    ]
