# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20170526_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='archivos/%Y/%m/%d'),
        ),
    ]
