# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20170527_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operacionmes',
            unique_together=set([('empresa', 'mes', 'anio')]),
        ),
    ]
