# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20170527_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='cobro',
            field=models.ManyToManyField(blank=True, to='sistema.Cobro'),
        ),
    ]
