# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20170529_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='archivos/%Y/%m/%d'),
        ),
    ]
