# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20170529_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='archivos/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
