# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20170531_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='codigodeposito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
