# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20170531_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
