# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20170622_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
