# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20170702_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estatus',
            field=models.CharField(max_length=10),
        ),
    ]
