# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20170705_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='autenticadpi',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='autenticafirma',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='constanciaingresos',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='formularios',
        ),
    ]
