# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20170709_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='numeroexpe',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
