# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_cobro_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='esta_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediente',
            name='esta_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
